{{ config
(
    materialized = 'table'
)
}}

WITH RankedProjects AS (
  SELECT
    DATE_TRUNC('day', t.BLOCK_TIMESTAMP) AS DATE,
    CASE WHEN c.ADDRESS IS NOT NULL THEN COALESCE(l.NAME, t.TO_ADDRESS)  
    WHEN to_double(VALUE) > 0 THEN 'EOA-EOA ETH transfer'
    ELSE 'empty_call'
    END AS PROJECT,
    SUM(to_double(RECEIPT_L1_FEE + RECEIPT_EFFECTIVE_GAS_PRICE * RECEIPT_GAS_USED)/1e18) AS ETH_FEES,
    ROW_NUMBER() OVER(PARTITION BY DATE_TRUNC('day', t.BLOCK_TIMESTAMP) ORDER BY SUM(to_double(RECEIPT_L1_FEE + RECEIPT_EFFECTIVE_GAS_PRICE * RECEIPT_GAS_USED)/1e18) DESC) AS RN
  FROM
    BASE.RAW.TRANSACTIONS t
    LEFT JOIN BASE.RAW.CONTRACTS c ON t.TO_ADDRESS = c.ADDRESS 
    LEFT JOIN BASEMETRICS.DBT.LABELS_APPS l ON t.TO_ADDRESS = l.ADDRESS
    WHERE (c.ADDRESS IS NOT NULL OR to_double(VALUE) > 0)
    AND DATE_TRUNC('DAY',t.BLOCK_TIMESTAMP) >= TO_TIMESTAMP('2024-09-01', 'YYYY-MM-DD') 
    AND DATE_TRUNC('DAY',BLOCK_TIMESTAMP) < CURRENT_DATE() 
  GROUP BY
    1, 2
),
GroupedProjects AS (
  SELECT
    DATE,
    CASE WHEN RN <= 10 THEN PROJECT ELSE 'Other' END AS PROJECT,
    SUM(ETH_FEES) AS ETH_FEES
  FROM
    RankedProjects
  GROUP BY
    1, 2
)
SELECT 
TO_VARCHAR(DATE, 'YYYY-MM-DD') as DATE, PROJECT, ETH_FEES
FROM
  GroupedProjects g
ORDER BY
  1 DESC, 2 DESC