{{ config
(
    materialized = 'incremental',
    unique_key = 'date'
)
}}

WITH overview AS (
SELECT
ACTIVITY_DATE AS DATE,
'bsc' AS CHAIN,
SUCCESS_TRANSACTIONS AS NUM_TXNS,
ACTIVE_ADDRESSES,
TOTAL_TRANSACTIONS / 86400 AS TPS
FROM BSC.METRICS.OVERVIEW
{% if is_incremental() %}
WHERE ACTIVITY_DATE >= CURRENT_DATE() - interval '3 day'
AND ACTIVITY_DATE < CURRENT_DATE() 
{% endif %}
{% if not is_incremental() %}
WHERE ACTIVITY_DATE < CURRENT_DATE() 
AND ACTIVITY_DATE >= TO_TIMESTAMP('2024-09-01', 'YYYY-MM-DD') 
{% endif %}
)

, mgas AS (
SELECT
DATE_TRUNC('DAY',BLOCK_TIMESTAMP) AS DATE,
(SUM(RECEIPT_GAS_USED) / 86400) / 1e6 AS MEGAGAS_USED_PER_SECOND
FROM BSC.RAW.TRANSACTIONS
{% if is_incremental() %}
WHERE DATE_TRUNC('DAY',BLOCK_TIMESTAMP) >= CURRENT_DATE() - interval '3 day'
AND DATE_TRUNC('DAY',BLOCK_TIMESTAMP) < CURRENT_DATE() 
{% endif %}
{% if not is_incremental() %}
WHERE DATE_TRUNC('DAY',BLOCK_TIMESTAMP) >= TO_TIMESTAMP('2024-09-01', 'YYYY-MM-DD') 
AND DATE_TRUNC('DAY',BLOCK_TIMESTAMP) < CURRENT_DATE() 
{% endif %}
GROUP BY 1
)

SELECT 
o.DATE,
CHAIN,
NUM_TXNS,
ACTIVE_ADDRESSES,
TPS,
MEGAGAS_USED_PER_SECOND
FROM overview o
INNER JOIN mgas m ON o.DATE = m.DATE