version: 2

sources:
  - name: arbitrum_decoded
    database: arbitrum
    schema: decoded
    freshness: # default freshness
      warn_after: { count: 12, period: hour }
      error_after: { count: 24, period: hour }
    tables:
      - name: traces
        loaded_at_field: block_timestamp
      - name: logs
        loaded_at_field: block_timestamp       

  - name: arbitrum_raw
    database: arbitrum
    schema: raw
    freshness: # default freshness
      warn_after: { count: 12, period: hour }
      error_after: { count: 24, period: hour }
    tables:
      - name: transactions
        loaded_at_field: block_timestamp
      - name: traces
        loaded_at_field: block_timestamp    
      - name: logs
        loaded_at_field: block_timestamp  

  - name: base_decoded
    database: base
    schema: decoded
    freshness: # default freshness
      warn_after: { count: 12, period: hour }
      error_after: { count: 24, period: hour }
    tables:
      - name: traces
        loaded_at_field: block_timestamp
      - name: logs
        loaded_at_field: block_timestamp       

  - name: base_raw
    database: base
    schema: raw
    freshness: # default freshness
      warn_after: { count: 12, period: hour }
      error_after: { count: 24, period: hour }
    tables:
      - name: transactions
        loaded_at_field: block_timestamp
      - name: traces
        loaded_at_field: block_timestamp    
      - name: logs
        loaded_at_field: block_timestamp 